In [1]:
import numpy as np

In [2]:
# Сгенерировать матрицу размером 4 × 9, заполненную целыми числами.
a = np.random.randint(-100, 100, (4,9))
print(a)

[[ 15  30 -78 -41 -30 -35  71 -83 -37]
 [  6 -15 -56 -69  20 -27 -70 -90 -30]
 [ 78 -16  17 -99 -10  58 -16  38 -37]
 [-33   3 -91 -34  52 -51  -2  60 -83]]


In [3]:
# Вывести на экран элемент с индексами [2, 6].
print(a[2,6])

-16


In [4]:
# Вывести на экран каждый второй элемент третьей строки матрицы.
print(a[3, 1::2])

[  3 -34 -51  60]


In [20]:
# Вывести на экран элементы последнего столбца в обратном порядке.
print(a[:, -1][::-1])

[[-37 -83  71 -35 -30 -41 -78  30  15]
 [-30 -90 -70 -27  20 -69 -56 -15   6]
 [-37  38 -16  58 -10 -99  17 -16  78]
 [-83  60  -2 -51  52 -34 -91   3 -33]]


In [6]:
# Изменить форму матрицы с 4 × 9 на 6 × 6.
b = a.reshape(6,6)
print(b)

[[ 15  30 -78 -41 -30 -35]
 [ 71 -83 -37   6 -15 -56]
 [-69  20 -27 -70 -90 -30]
 [ 78 -16  17 -99 -10  58]
 [-16  38 -37 -33   3 -91]
 [-34  52 -51  -2  60 -83]]


In [7]:
# Возвести каждый элемент матрицы в заданную степень.
c = b ** int(input())
print(c)

[[   3375   27000 -474552  -68921  -27000  -42875]
 [ 357911 -571787  -50653     216   -3375 -175616]
 [-328509    8000  -19683 -343000 -729000  -27000]
 [ 474552   -4096    4913 -970299   -1000  195112]
 [  -4096   54872  -50653  -35937      27 -753571]
 [ -39304  140608 -132651      -8  216000 -571787]]


In [8]:
# Найти минимум на главной диагонали.
print(np.min(c.diagonal()))

-970299


In [9]:
# Найти максимальный элемент в предпоследнем столбце.
print(np.max(c[:, -2]))

216000


In [13]:
# Определить, образуют ли элементы сжатого до одной оси массива невозрастающую последовательность.
d = np.diff(c)
print(np.all(d >= 0 ))

False


In [11]:
# Подсчитать произведение ненулевых элементов на побочной диагонали.
e = np.fliplr(c).diagonal()
print(np.prod(e[e != 0]))

-353945088
