In [14]:
import numpy as np

In [15]:
# Сгенерировать матрицу размером 4 × 9, заполненную целыми числами.
a = np.random.randint(-100, 100, (4,9))
print(a)

[[ 36 -16  77  59  51  86  41 -21 -76]
 [ 15 -26 -98 -29 -33  79 -59  60 -90]
 [-32  65   0 -88  24   2  38 -73 -79]
 [ 94  14  13 -76 -59  90 -14  74 -71]]


In [16]:
# Вывести на экран элемент с индексами [2, 6].
print(a[2,6])

38


In [17]:
# Вывести на экран каждый второй элемент третьей строки матрицы.
print(a[3, 1::2])

[ 14 -76  90  74]


In [18]:
# Вывести на экран элементы последнего столбца в обратном порядке.
print(a[:, -1][::-1])

[-71 -79 -90 -76]


In [19]:
# Изменить форму матрицы с 4 × 9 на 6 × 6.
b = a.reshape(6,6)
print(b)

[[ 36 -16  77  59  51  86]
 [ 41 -21 -76  15 -26 -98]
 [-29 -33  79 -59  60 -90]
 [-32  65   0 -88  24   2]
 [ 38 -73 -79  94  14  13]
 [-76 -59  90 -14  74 -71]]


In [20]:
# Возвести каждый элемент матрицы в заданную степень.
c = b ** int(input())
print(c)

[[  46656   -4096  456533  205379  132651  636056]
 [  68921   -9261 -438976    3375  -17576 -941192]
 [ -24389  -35937  493039 -205379  216000 -729000]
 [ -32768  274625       0 -681472   13824       8]
 [  54872 -389017 -493039  830584    2744    2197]
 [-438976 -205379  729000   -2744  405224 -357911]]


In [21]:
# Найти минимум на главной диагонали.
print(np.min(c.diagonal()))

-681472


In [22]:
# Найти максимальный элемент в предпоследнем столбце.
print(np.max(c[:, -2]))

405224


In [23]:
# Определить, образуют ли элементы сжатого до одной оси массива невозрастающую последовательность.
d = np.diff(c)
print(np.all(d >= 0 ))

False


In [24]:
# Подсчитать произведение ненулевых элементов на побочной диагонали.
e = np.fliplr(c).diagonal()
print(np.prod(e[e != 0]))

-1046759180742594560
