In [116]:
import numpy as np

In [117]:
# Сгенерировать матрицу размером 4 × 9, заполненную целыми числами.
a = np.random.randint(-100, 100, (4,9))
print(a)

[[ 45  68  20 -29 -18  39  43 -94  63]
 [ 10 -14 -92  40 -96  50  78 -75 -59]
 [-98  57  45  49 -49  33  76  -9 -32]
 [-41  18  80  61  57 -22  42 -11 -36]]


In [118]:
# Вывести на экран элемент с индексами [2, 6].
print(a[2,6])

76


In [119]:
# Вывести на экран каждый второй элемент третьей строки матрицы.
print(a[3, 1::2])

[ 18  61 -22 -11]


In [120]:
# Вывести на экран элементы последнего столбца в обратном порядке.
print(a[:, -1][::-1])

[-36 -32 -59  63]


In [121]:
# Изменить форму матрицы с 4 × 9 на 6 × 6.
b = a.reshape(6,6)
print(b)

[[ 45  68  20 -29 -18  39]
 [ 43 -94  63  10 -14 -92]
 [ 40 -96  50  78 -75 -59]
 [-98  57  45  49 -49  33]
 [ 76  -9 -32 -41  18  80]
 [ 61  57 -22  42 -11 -36]]


In [122]:
# Возвести каждый элемент матрицы в заданную степень.
c = b ** int(input())
print(c)

[[2025 4624  400  841  324 1521]
 [1849 8836 3969  100  196 8464]
 [1600 9216 2500 6084 5625 3481]
 [9604 3249 2025 2401 2401 1089]
 [5776   81 1024 1681  324 6400]
 [3721 3249  484 1764  121 1296]]


In [123]:
# Найти минимум на главной диагонали.
print(np.min(c.diagonal()))

324


In [128]:
# Найти максимальный элемент в предпоследнем столбце.
print(np.max(c[:, -2]))

5625


In [125]:
# Определить, образуют ли элементы сжатого до одной оси массива невозрастающую последовательность.
d = c.flatten()
print(all(d[i] <= d[i+1] for i in range(len(d) - 1)))

False


In [127]:
# Подсчитать произведение ненулевых элементов на побочной диагонали.
e = np.fliplr(c).diagonal()
print(np.prod(e[e != 0]))

1106991298803171600
